FROM openjdk:17-jdk-slim as build
COPY . .
RUN ./gradlew clean build -x test

FROM openjdk:17-jdk-slim
COPY --from=build build/libs/demo-0.0.1-SNAPSHOT.jar app.jar
ENV MODE="CMD"
CMD java -jar app.jar